### ISSUE TITLE
Solução Erro imagens do Vercel.

### ISSUE THREAD

**Issue by GuilhermeHalter** [joaobagatoli07/coffee-app#5]
Olá, grupo! Tudo bem?

Sou da sala de vocês e, durante a apresentação do projeto para o professor, vocês mencionaram que houve um erro com as imagens ao fazer o deploy para o Vercel. Encontrei o mesmo problema no meu projeto. Esse erro ocorre porque o Vercel não suporta imagens tão grandes quanto as que vocês estão utilizando.

Para resolver esse problema, sugiro fazer o upload das imagens em um serviço de armazenamento em nuvem. Eu, por exemplo, utilizei no meu projeto o **Firebase** da Google para armazenar as imagens e puxa-las usando a URL fornecida pelo serviço.

Espero que essa dica ajude!

Abraços.

**Comment by joaobagatoli07** [comment]
Olá Guilherme.

Muito obrigado pela dica! Iremos colocar em prática.

Até mais!
